"""Nasdaq Symbol Screener Filter Options.

Generated from the filter definitions the Nasdaq screener endpoints publish.
Each filter contributes a ``Literal`` of lower-snake keys, a map from those
keys to the API values, and a ``[{label, value}]`` list for widget dropdowns.
"""

from typing import Literal

ETF_FUND_FAMILY = Literal[
    "all_funds",
    "ishares",
    "state_street",
    "vanguard_etfs",
    "powershares",
    "wisdom_tree",
    "proshares",
    "market_vectors_van_eck_global",
    "guggenheim",
    "currencyshares",
    "schwab_etfs",
    "first_trust",
    "alps",
    "ipath_etns",
    "direxion_funds",
    "flexshares",
    "etf_securities",
    "united_states_commodities_funds",
    "etracs_etns_ubs",
    "global_x_funds",
    "eg_shares",
    "elements_etns",
    "velocityshares",
    "advisorshares",
    "index_iq",
    "teucrium",
    "quantshares",
    "purefunds",
    "victoryshares",
]

ETF_FUND_FAMILY_MAP: dict[str, str] = {
    "all_funds": "all",
    "ishares": "iShares ",
    "state_street": "State Street",
    "vanguard_etfs": "Vanguard ETFs",
    "powershares": "PowerShares",
    "wisdom_tree": "Wisdom Tree",
    "proshares": "ProShares",
    "market_vectors_van_eck_global": "Market Vectors Van Eck Global",
    "guggenheim": "Guggenheim",
    "currencyshares": "CurrencyShares",
    "schwab_etfs": "Schwab ETFs",
    "first_trust": "First Trust",
    "alps": "ALPS",
    "ipath_etns": "iPath ETNs",
    "direxion_funds": "Direxion Funds",
    "flexshares": "FlexShares",
    "etf_securities": "ETF Securities",
    "united_states_commodities_funds": "United States Commodities Funds",
    "etracs_etns_ubs": "Etracs ETNs - UBS",
    "global_x_funds": "Global X Funds",
    "eg_shares": "EG Shares",
    "elements_etns": "Elements ETNs",
    "velocityshares": "VelocityShares",
    "advisorshares": "AdvisorShares",
    "index_iq": "Index IQ",
    "teucrium": "Teucrium",
    "quantshares": "QuantShares",
    "purefunds": "PureFunds",
    "victoryshares": "VictoryShares",
}

ETF_FUND_FAMILY_CHOICES: list[dict] = [
    {"label": "All funds", "value": "all_funds"},
    {"label": "iShares", "value": "ishares"},
    {"label": "State Street", "value": "state_street"},
    {"label": "Vanguard ETFs", "value": "vanguard_etfs"},
    {"label": "PowerShares", "value": "powershares"},
    {"label": "Wisdom Tree", "value": "wisdom_tree"},
    {"label": "ProShares", "value": "proshares"},
    {
        "label": "Market Vectors Van Eck Global",
        "value": "market_vectors_van_eck_global",
    },
    {"label": "Guggenheim", "value": "guggenheim"},
    {"label": "CurrencyShares", "value": "currencyshares"},
    {"label": "Schwab ETFs", "value": "schwab_etfs"},
    {"label": "First Trust", "value": "first_trust"},
    {"label": "ALPS", "value": "alps"},
    {"label": "iPath ETNs", "value": "ipath_etns"},
    {"label": "Direxion Funds", "value": "direxion_funds"},
    {"label": "FlexShares", "value": "flexshares"},
    {"label": "ETF Securities", "value": "etf_securities"},
    {
        "label": "United States Commodities Funds",
        "value": "united_states_commodities_funds",
    },
    {"label": "Etracs ETNs - UBS", "value": "etracs_etns_ubs"},
    {"label": "Global X Funds", "value": "global_x_funds"},
    {"label": "EG Shares", "value": "eg_shares"},
    {"label": "Elements ETNs", "value": "elements_etns"},
    {"label": "VelocityShares", "value": "velocityshares"},
    {"label": "AdvisorShares", "value": "advisorshares"},
    {"label": "Index IQ", "value": "index_iq"},
    {"label": "Teucrium", "value": "teucrium"},
    {"label": "QuantShares", "value": "quantshares"},
    {"label": "PureFunds", "value": "purefunds"},
    {"label": "VictoryShares", "value": "victoryshares"},
]

ETF_SECTOR = Literal[
    "all_sectors",
    "agriculture",
    "alternative_investments",
    "asia",
    "biotech",
    "bonds",
    "commodities",
    "construction",
    "consumer_discretionary",
    "consumer_non_cyclical",
    "consumer_services",
    "consumer_staples",
    "currency",
    "defense",
    "emerging_markets",
    "energy",
    "environmental",
    "europe",
    "financial_services",
    "grains",
    "healthcare",
    "hotels_and_gambling",
    "income",
    "industrial",
    "international",
    "large_cap",
    "managed_etfs",
    "materials",
    "meats",
    "metals",
    "mid_cap",
    "mixed_asset",
    "multi_cap",
    "natural_resources",
    "non_taxable",
    "power",
    "precious_metals",
    "real_estate",
    "small_cap",
    "taxable_bonds",
    "technology",
    "telecommunications",
    "transportation",
    "utilities",
]

ETF_SECTOR_MAP: dict[str, str] = {
    "all_sectors": "all",
    "agriculture": "agriculture",
    "alternative_investments": "alternative-investments",
    "asia": "asia",
    "biotech": "biotech",
    "bonds": "bonds",
    "commodities": "commodities",
    "construction": "construction",
    "consumer_discretionary": "consumer-discretionary",
    "consumer_non_cyclical": "consumer-non-cyclical",
    "consumer_services": "consumer-services",
    "consumer_staples": "consumer-staples",
    "currency": "currency",
    "defense": "defense",
    "emerging_markets": "emerging-markets",
    "energy": "energy",
    "environmental": "environmental",
    "europe": "europe",
    "financial_services": "financial-services",
    "grains": "grains",
    "healthcare": "healthcare",
    "hotels_and_gambling": "hotels-gambling",
    "income": "income",
    "industrial": "Industrial",
    "international": "international",
    "large_cap": "large-cap",
    "managed_etfs": "managed-etfs",
    "materials": "materials",
    "meats": "meats",
    "metals": "metals",
    "mid_cap": "mid-cap",
    "mixed_asset": "mixed-asset",
    "multi_cap": "multi-cap",
    "natural_resources": "natural-resources",
    "non_taxable": "non-taxable",
    "power": "power",
    "precious_metals": "precious-metals",
    "real_estate": "real-estate",
    "small_cap": "small-cap",
    "taxable_bonds": "taxable-bonds",
    "technology": "technology",
    "telecommunications": "telecommunications",
    "transportation": "transportation",
    "utilities": "utilities",
}

ETF_SECTOR_CHOICES: list[dict] = [
    {"label": "All Sectors", "value": "all_sectors"},
    {"label": "Agriculture", "value": "agriculture"},
    {"label": "Alternative Investments", "value": "alternative_investments"},
    {"label": "Asia", "value": "asia"},
    {"label": "Biotech", "value": "biotech"},
    {"label": "Bonds", "value": "bonds"},
    {"label": "Commodities", "value": "commodities"},
    {"label": "Construction", "value": "construction"},
    {"label": "Consumer Discretionary", "value": "consumer_discretionary"},
    {"label": "Consumer Non-Cyclical", "value": "consumer_non_cyclical"},
    {"label": "Consumer Services", "value": "consumer_services"},
    {"label": "Consumer Staples", "value": "consumer_staples"},
    {"label": "Currency", "value": "currency"},
    {"label": "Defense", "value": "defense"},
    {"label": "Emerging Markets", "value": "emerging_markets"},
    {"label": "Energy", "value": "energy"},
    {"label": "Environmental", "value": "environmental"},
    {"label": "Europe", "value": "europe"},
    {"label": "Financial Services", "value": "financial_services"},
    {"label": "Grains", "value": "grains"},
    {"label": "Healthcare", "value": "healthcare"},
    {"label": "Hotels & Gambling", "value": "hotels_and_gambling"},
    {"label": "Income", "value": "income"},
    {"label": "Industrial", "value": "industrial"},
    {"label": "International", "value": "international"},
    {"label": "Large Cap", "value": "large_cap"},
    {"label": "Managed ETFs", "value": "managed_etfs"},
    {"label": "Materials", "value": "materials"},
    {"label": "Meats", "value": "meats"},
    {"label": "Metals", "value": "metals"},
    {"label": "Mid Cap", "value": "mid_cap"},
    {"label": "Mixed Asset", "value": "mixed_asset"},
    {"label": "Multi Cap", "value": "multi_cap"},
    {"label": "Natural Resources", "value": "natural_resources"},
    {"label": "Non-Taxable", "value": "non_taxable"},
    {"label": "Power", "value": "power"},
    {"label": "Precious Metals", "value": "precious_metals"},
    {"label": "Real Estate", "value": "real_estate"},
    {"label": "Small Cap", "value": "small_cap"},
    {"label": "Taxable Bonds", "value": "taxable_bonds"},
    {"label": "Technology", "value": "technology"},
    {"label": "Telecommunications", "value": "telecommunications"},
    {"label": "Transportation", "value": "transportation"},
    {"label": "Utilities", "value": "utilities"},
]

ETF_PERFORMANCE = Literal[
    "all_performance",
    "less_than_neg_50",
    "between_neg_50_and_neg_25",
    "between_neg_25_and_neg_10",
    "between_neg_10_and_0",
    "between_0_and_5",
    "between_5_and_10",
    "between_10_and_15",
    "between_15_and_20",
    "between_20_and_25",
    "more_than_25",
]

ETF_PERFORMANCE_MAP: dict[str, str] = {
    "all_performance": "all",
    "less_than_neg_50": "ry1",
    "between_neg_50_and_neg_25": "ry2",
    "between_neg_25_and_neg_10": "ry3",
    "between_neg_10_and_0": "ry4",
    "between_0_and_5": "ry5",
    "between_5_and_10": "ry6",
    "between_10_and_15": "ry7",
    "between_15_and_20": "ry8",
    "between_20_and_25": "ry9",
    "more_than_25": "ry10",
}

ETF_PERFORMANCE_CHOICES: list[dict] = [
    {"label": "All Performance", "value": "all_performance"},
    {"label": "less than -50", "value": "less_than_neg_50"},
    {"label": "between -50 and -25", "value": "between_neg_50_and_neg_25"},
    {"label": "between -25 and -10", "value": "between_neg_25_and_neg_10"},
    {"label": "between -10 and 0", "value": "between_neg_10_and_0"},
    {"label": "between 0 and 5", "value": "between_0_and_5"},
    {"label": "between 5 and 10", "value": "between_5_and_10"},
    {"label": "between 10 and 15", "value": "between_10_and_15"},
    {"label": "between 15 and 20", "value": "between_15_and_20"},
    {"label": "between 20 and 25", "value": "between_20_and_25"},
    {"label": "more than 25", "value": "more_than_25"},
]

ETF_ASSET_CLASS = Literal[
    "all_asset_classes",
    "bond",
    "commodity",
    "currency",
    "equity",
    "fixed_income",
    "liquidated_fund",
    "multi_asset",
    "volatility",
]

ETF_ASSET_CLASS_MAP: dict[str, str] = {
    "all_asset_classes": "all",
    "bond": "bond",
    "commodity": "commodity",
    "currency": "currency",
    "equity": "equity",
    "fixed_income": "fixed",
    "liquidated_fund": "liquidated",
    "multi_asset": "multi-asset",
    "volatility": "volatility",
}

ETF_ASSET_CLASS_CHOICES: list[dict] = [
    {"label": "All Asset Classes", "value": "all_asset_classes"},
    {"label": "Bond", "value": "bond"},
    {"label": "Commodity", "value": "commodity"},
    {"label": "Currency", "value": "currency"},
    {"label": "Equity", "value": "equity"},
    {"label": "Fixed Income", "value": "fixed_income"},
    {"label": "Liquidated Fund", "value": "liquidated_fund"},
    {"label": "Multi-Asset", "value": "multi_asset"},
    {"label": "Volatility", "value": "volatility"},
]

ETF_REGION = Literal[
    "all_region",
    "africa",
    "asia_pacific",
    "europe_australia_and_far_east",
    "europe",
    "global",
    "latin_america",
    "middle_east",
    "north_america",
]

ETF_REGION_MAP: dict[str, str] = {
    "all_region": "all",
    "africa": "africa",
    "asia_pacific": "asia-pacific",
    "europe_australia_and_far_east": "EAFE",
    "europe": "europe",
    "global": "global",
    "latin_america": "latin-america",
    "middle_east": "middle-east",
    "north_america": "north-america",
}

ETF_REGION_CHOICES: list[dict] = [
    {"label": "All Region", "value": "all_region"},
    {"label": "Africa", "value": "africa"},
    {"label": "Asia-Pacific", "value": "asia_pacific"},
    {
        "label": "Europe-Australia and Far East",
        "value": "europe_australia_and_far_east",
    },
    {"label": "Europe", "value": "europe"},
    {"label": "Global", "value": "global"},
    {"label": "Latin America", "value": "latin_america"},
    {"label": "Middle East", "value": "middle_east"},
    {"label": "North America", "value": "north_america"},
]

FUND_TYPE = Literal[
    "all_funds",
    "money_market_fund",
    "managed_accounts",
    "unit_investment_trust_uit",
    "annuity",
    "managed_fund",
    "structured_product",
    "nextshares_exchange_traded",
    "alternative_investment",
]

FUND_TYPE_MAP: dict[str, str] = {
    "all_funds": "ALL",
    "money_market_fund": "$$",
    "managed_accounts": "MA",
    "unit_investment_trust_uit": "6",
    "annuity": "AN",
    "managed_fund": "MF",
    "structured_product": "US",
    "nextshares_exchange_traded": "5",
    "alternative_investment": "AP",
}

FUND_TYPE_CHOICES: list[dict] = [
    {"label": "All Funds", "value": "all_funds"},
    {"label": "Money Market Fund", "value": "money_market_fund"},
    {"label": "Managed Accounts", "value": "managed_accounts"},
    {"label": "Unit Investment Trust (UIT)", "value": "unit_investment_trust_uit"},
    {"label": "Annuity", "value": "annuity"},
    {"label": "Managed Fund", "value": "managed_fund"},
    {"label": "Structured Product", "value": "structured_product"},
    {"label": "NextShares Exchange Traded", "value": "nextshares_exchange_traded"},
    {"label": "Alternative Investment", "value": "alternative_investment"},
]

INDEX_TYPE = Literal[
    "all_indexes",
    "international",
    "us",
]

INDEX_TYPE_MAP: dict[str, str] = {
    "all_indexes": "ALL",
    "international": "GM",
    "us": "US",
}

INDEX_TYPE_CHOICES: list[dict] = [
    {"label": "All Indexes", "value": "all_indexes"},
    {"label": "International", "value": "international"},
    {"label": "US", "value": "us"},
]

STOCK_REGION = Literal[
    "africa",
    "asia",
    "australia_and_south_pacific",
    "caribbean",
    "europe",
    "middle_east",
    "north_america",
    "south_america",
]

STOCK_REGION_MAP: dict[str, str] = {
    "africa": "africa",
    "asia": "asia",
    "australia_and_south_pacific": "australia_and_south_pacific",
    "caribbean": "caribbean",
    "europe": "europe",
    "middle_east": "middle_east",
    "north_america": "north_america",
    "south_america": "south_america",
}

STOCK_REGION_CHOICES: list[dict] = [
    {"label": "Africa", "value": "africa"},
    {"label": "Asia", "value": "asia"},
    {"label": "Australia and South Pacific", "value": "australia_and_south_pacific"},
    {"label": "Caribbean", "value": "caribbean"},
    {"label": "Europe", "value": "europe"},
    {"label": "Middle East", "value": "middle_east"},
    {"label": "North America", "value": "north_america"},
    {"label": "South America", "value": "south_america"},
]

STOCK_COUNTRY = Literal[
    "united_states",
    "china",
    "canada",
    "france",
    "hong_kong",
    "bermuda",
    "switzerland",
    "ireland",
    "taiwan",
    "cayman_islands",
    "gibraltar",
    "brazil",
    "belgium",
    "malaysia",
    "united_arab_emirates",
    "united_kingdom",
    "israel",
    "luxembourg",
    "singapore",
    "netherlands",
    "denmark",
    "germany",
    "australia",
    "japan",
    "argentina",
    "puerto_rico",
    "italy",
    "greece",
    "new_zealand",
    "british_virgin_islands",
    "jersey",
    "cyprus",
    "south_korea",
    "uruguay",
    "guernsey",
    "macau",
    "sweden",
    "costa_rica",
    "u_s_virgin_islands",
    "cambodia",
    "kazakhstan",
    "spain",
    "mexico",
    "turkey",
    "jordan",
    "finland",
    "south_africa",
    "india",
    "curacao",
    "norway",
    "bahamas",
    "indonesia",
    "philippines",
]

STOCK_COUNTRY_MAP: dict[str, str] = {
    "united_states": "united_states",
    "china": "china",
    "canada": "canada",
    "france": "france",
    "hong_kong": "hong_kong",
    "bermuda": "bermuda",
    "switzerland": "switzerland",
    "ireland": "ireland",
    "taiwan": "taiwan",
    "cayman_islands": "cayman_islands",
    "gibraltar": "gibraltar",
    "brazil": "brazil",
    "belgium": "belgium",
    "malaysia": "malaysia",
    "united_arab_emirates": "united_arab_emirates",
    "united_kingdom": "united_kingdom",
    "israel": "israel",
    "luxembourg": "luxembourg",
    "singapore": "singapore",
    "netherlands": "netherlands",
    "denmark": "denmark",
    "germany": "germany",
    "australia": "australia",
    "japan": "japan",
    "argentina": "argentina",
    "puerto_rico": "puerto_rico",
    "italy": "italy",
    "greece": "greece",
    "new_zealand": "new_zealand",
    "british_virgin_islands": "british_virgin_islands",
    "jersey": "jersey",
    "cyprus": "cyprus",
    "south_korea": "south_korea",
    "uruguay": "uruguay",
    "guernsey": "guernsey",
    "macau": "macau",
    "sweden": "sweden",
    "costa_rica": "costa_rica",
    "u_s_virgin_islands": "u.s._virgin_islands",
    "cambodia": "cambodia",
    "kazakhstan": "kazakhstan",
    "spain": "spain",
    "mexico": "mexico",
    "turkey": "turkey",
    "jordan": "jordan",
    "finland": "finland",
    "south_africa": "south_africa",
    "india": "india",
    "curacao": "curacao",
    "norway": "norway",
    "bahamas": "bahamas",
    "indonesia": "indonesia",
    "philippines": "philippines",
}

STOCK_COUNTRY_CHOICES: list[dict] = [
    {"label": "United States", "value": "united_states"},
    {"label": "China", "value": "china"},
    {"label": "Canada", "value": "canada"},
    {"label": "France", "value": "france"},
    {"label": "Hong Kong", "value": "hong_kong"},
    {"label": "Bermuda", "value": "bermuda"},
    {"label": "Switzerland", "value": "switzerland"},
    {"label": "Ireland", "value": "ireland"},
    {"label": "Taiwan", "value": "taiwan"},
    {"label": "Cayman Islands", "value": "cayman_islands"},
    {"label": "Gibraltar", "value": "gibraltar"},
    {"label": "Brazil", "value": "brazil"},
    {"label": "Belgium", "value": "belgium"},
    {"label": "Malaysia", "value": "malaysia"},
    {"label": "United Arab Emirates", "value": "united_arab_emirates"},
    {"label": "United Kingdom", "value": "united_kingdom"},
    {"label": "Israel", "value": "israel"},
    {"label": "Luxembourg", "value": "luxembourg"},
    {"label": "Singapore", "value": "singapore"},
    {"label": "Netherlands", "value": "netherlands"},
    {"label": "Denmark", "value": "denmark"},
    {"label": "Germany", "value": "germany"},
    {"label": "Australia", "value": "australia"},
    {"label": "Japan", "value": "japan"},
    {"label": "Argentina", "value": "argentina"},
    {"label": "Puerto Rico", "value": "puerto_rico"},
    {"label": "Italy", "value": "italy"},
    {"label": "Greece", "value": "greece"},
    {"label": "New Zealand", "value": "new_zealand"},
    {"label": "British Virgin Islands", "value": "british_virgin_islands"},
    {"label": "Jersey", "value": "jersey"},
    {"label": "Cyprus", "value": "cyprus"},
    {"label": "South Korea", "value": "south_korea"},
    {"label": "Uruguay", "value": "uruguay"},
    {"label": "Guernsey", "value": "guernsey"},
    {"label": "Macau", "value": "macau"},
    {"label": "Sweden", "value": "sweden"},
    {"label": "Costa Rica", "value": "costa_rica"},
    {"label": "U.S. Virgin Islands", "value": "u_s_virgin_islands"},
    {"label": "Cambodia", "value": "cambodia"},
    {"label": "Kazakhstan", "value": "kazakhstan"},
    {"label": "Spain", "value": "spain"},
    {"label": "Mexico", "value": "mexico"},
    {"label": "Turkey", "value": "turkey"},
    {"label": "Jordan", "value": "jordan"},
    {"label": "Finland", "value": "finland"},
    {"label": "South Africa", "value": "south_africa"},
    {"label": "India", "value": "india"},
    {"label": "Curacao", "value": "curacao"},
    {"label": "Norway", "value": "norway"},
    {"label": "Bahamas", "value": "bahamas"},
    {"label": "Indonesia", "value": "indonesia"},
    {"label": "Philippines", "value": "philippines"},
]

STOCK_EXCHANGE = Literal[
    "nasdaq",
    "nyse",
    "amex",
]

STOCK_EXCHANGE_MAP: dict[str, str] = {
    "nasdaq": "NASDAQ",
    "nyse": "NYSE",
    "amex": "AMEX",
}

STOCK_EXCHANGE_CHOICES: list[dict] = [
    {"label": "NASDAQ", "value": "nasdaq"},
    {"label": "NYSE", "value": "nyse"},
    {"label": "AMEX", "value": "amex"},
]

STOCK_SECTOR = Literal[
    "technology",
    "telecommunications",
    "healthcare",
    "financials",
    "real_estate",
    "consumer_discretionary",
    "consumer_staples",
    "industrials",
    "basic_materials",
    "energy",
    "utilities",
]

STOCK_SECTOR_MAP: dict[str, str] = {
    "technology": "technology",
    "telecommunications": "telecommunications",
    "healthcare": "health_care",
    "financials": "finance",
    "real_estate": "real_estate",
    "consumer_discretionary": "consumer_discretionary",
    "consumer_staples": "consumer_staples",
    "industrials": "industrials",
    "basic_materials": "basic_materials",
    "energy": "energy",
    "utilities": "utilities",
}

STOCK_SECTOR_CHOICES: list[dict] = [
    {"label": "Technology", "value": "technology"},
    {"label": "Telecommunications", "value": "telecommunications"},
    {"label": "Healthcare", "value": "healthcare"},
    {"label": "Financials", "value": "financials"},
    {"label": "Real Estate", "value": "real_estate"},
    {"label": "Consumer Discretionary", "value": "consumer_discretionary"},
    {"label": "Consumer Staples", "value": "consumer_staples"},
    {"label": "Industrials", "value": "industrials"},
    {"label": "Basic Materials", "value": "basic_materials"},
    {"label": "Energy", "value": "energy"},
    {"label": "Utilities", "value": "utilities"},
]

STOCK_RECOMMENDATION = Literal[
    "strong_buy",
    "hold",
    "buy",
    "sell",
    "strong_sell",
]

STOCK_RECOMMENDATION_MAP: dict[str, str] = {
    "strong_buy": "strong_buy",
    "hold": "hold",
    "buy": "buy",
    "sell": "sell",
    "strong_sell": "strong_sell",
}

STOCK_RECOMMENDATION_CHOICES: list[dict] = [
    {"label": "Strong Buy", "value": "strong_buy"},
    {"label": "Hold", "value": "hold"},
    {"label": "Buy", "value": "buy"},
    {"label": "Sell", "value": "sell"},
    {"label": "Strong Sell", "value": "strong_sell"},
]

STOCK_MARKET_CAP = Literal[
    "mega_usd_200b",
    "large_usd_10b_usd_200b",
    "medium_usd_2b_usd_10b",
    "small_usd_300m_usd_2b",
    "micro_usd_50m_usd_300m",
    "nano_usd_50m",
]

STOCK_MARKET_CAP_MAP: dict[str, str] = {
    "mega_usd_200b": "mega",
    "large_usd_10b_usd_200b": "large",
    "medium_usd_2b_usd_10b": "mid",
    "small_usd_300m_usd_2b": "small",
    "micro_usd_50m_usd_300m": "micro",
    "nano_usd_50m": "nano",
}

STOCK_MARKET_CAP_CHOICES: list[dict] = [
    {"label": "Mega (>$200B)", "value": "mega_usd_200b"},
    {"label": "Large ($10B-$200B)", "value": "large_usd_10b_usd_200b"},
    {"label": "Medium ($2B-$10B)", "value": "medium_usd_2b_usd_10b"},
    {"label": "Small ($300M-$2B)", "value": "small_usd_300m_usd_2b"},
    {"label": "Micro ($50M-$300M)", "value": "micro_usd_50m_usd_300m"},
    {"label": "Nano (<$50M)", "value": "nano_usd_50m"},
]

STOCK_SUB_CATEGORY = Literal[
    "global_select",
    "global_market",
    "capital_market",
    "adr",
]

STOCK_SUB_CATEGORY_MAP: dict[str, str] = {
    "global_select": "NGS",
    "global_market": "NGM",
    "capital_market": "NCM",
    "adr": "ADR",
}

STOCK_SUB_CATEGORY_CHOICES: list[dict] = [
    {"label": "Global Select", "value": "global_select"},
    {"label": "Global Market", "value": "global_market"},
    {"label": "Capital Market", "value": "capital_market"},
    {"label": "ADR", "value": "adr"},
]
