[tool.poetry]
name = "openbb-government"
version = "1.4.2"
description = "Government extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_government" }]

[tool.poetry.dependencies]
python = ">=3.9.21,<3.13"
openbb-core = "^1.4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
government = "openbb_government.government_router:router"

[tool.poetry.plugins."openbb_charting_extension"]
government = "openbb_government.government_views:GovernmentViews"
