#!/bin/bash

# Get the current user and group r
CURRENT_USER=$(id -u)
CURRENT_GROUP=$(id -g)
CURRENT_USER_HOME=$(eval echo ~$USER)

# Download Docker Compose files
curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml
curl -o docker-compose.x11.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.x11.yaml


docker compose -f docker-compose.yaml -f docker-compose.x11.yaml -p openbb up -d

# Change ownership of the current user /home folder
sudo chown -R $CURRENT_USER:$CURRENT_GROUP $CURRENT_USER_HOME/OpenBBUserData/
sudo chown -R $CURRENT_USER:$CURRENT_GROUP $CURRENT_USER_HOME/.openbb_terminal/

docker attach openbb-openbb-1