[pytest]
addopts = -p no:warnings
markers =
    linux: tests that are not stable on Windows
    integration: OpenBB Platform integration test marker
    requires_pandas: test requires the openbb-core[pandas] extra
    requires_extensions: test requires non-core OpenBB packages installed (providers/extensions)
testpaths =
    tests
    openbb_platform/**/tests
