cd_CHOICES = [
    "stocks/",
    "stocks/disc/",
    "stocks/ta/",
    "stocks/dd/",
    "forex",
    "forex/oanda",
    "crypto/",
    "crypto/ta",
    "crypto/dd",
    "crypto/ov",
    "crypto/disc",
    "crypto/onchain",
    "crypto/defi",
    "crypto/nft",
    "crypto/pred",
]
