[tool.poetry]
name = "openbb-congress-gov"
version = "1.0.0"
description = "Congress.gov Provider Extension for the OpenBB Platform"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_congress_gov" }]

[tool.poetry.dependencies]
python = ">=3.9.21,<3.13"
openbb-core = "^1.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
congress_gov = "openbb_congress_gov:congress_gov_provider"

[tool.poetry.plugins."openbb_core_extension"]
uscongress = "openbb_congress_gov.router.congress_gov_router:router"
