// Auto-generated by qa/scripts/generate_quant_ts_types.py
// Keep this file additive and import explicit interfaces from quant.ts as needed.

export interface RunLatestMetaGenerated {
  run_id: unknown;
  run_uid: unknown;
  model_name: unknown;
  as_of_date: unknown;
  status: unknown;
  artifact_contract_version: unknown;
  required_artifacts_ready: unknown;
  universe_stage_counts: unknown;
  artifact_completeness: unknown;
  message: unknown;
}

export interface RunLatestConstraintsGenerated {
  run_id: unknown;
  model_name: unknown;
  status: unknown;
  message: unknown;
  items: unknown;
  liquidity_clip_ratio: unknown;
  risk_contribution_max: unknown;
  top_risk_contribution: unknown;
  liquidity_adv_top: unknown;
}

export interface DashboardSnapshotGenerated {
  run_id: unknown;
  run_uid: unknown;
  model_name: unknown;
  as_of_utc: unknown;
  total_return: unknown;
  cagr: unknown;
  sharpe: unknown;
  sortino: unknown;
  max_drawdown: unknown;
  volatility: unknown;
  turnover: unknown;
  win_rate: unknown;
  exposure: unknown;
  risk_contrib_top10: unknown;
  constraint_bindings: unknown;
  ic_rolling: unknown;
  currency: unknown;
}

export interface RunAuditGenerated {
  run_id: unknown;
  status: unknown;
  message: unknown;
  events: unknown;
}
