"""EDGAR full-text search lookup data: filing categories and location codes."""

FTS_CATEGORIES = [
    {
        "label": "Exclude insider equity awards, transactions, and ownership (Section 16 Reports)",
        "value": "-3,-4,-5",
    },
    {
        "label": "All annual, quarterly, and current reports",
        "value": "1-K,1-SA,1-U,1-Z,1-Z-W,10-D,10-K,10-KT,10-Q,10-QT,11-K,11-KT,13F-HR,13F-NT,15-12B,15-12G,15-15D,15F-12B,15F-12G,15F-15D,18-K,20-F,24F-2NT,25,25-NSE,40-17F2,40-17G,40-F,6-K,8-K,8-K12G3,8-K15D5,ABS-15G,ABS-EE,ANNLRPT,DSTRBRPT,IRANNOTICE,N-30B-2,N-30D,N-CEN,N-CSR,N-CSRS,N-MFP,N-MFP1,N-MFP2,N-PX,N-Q,NPORT-EX,NSAR-A,NSAR-B,NSAR-U,NT 10-D,NT 10-K,NT 10-Q,NT 11-K,NT 20-F,QRTLYRPT,SD,SP 15D2",
    },
    {
        "label": "Insider equity awards, transactions, and ownership (Section 16 Reports)",
        "value": "3,4,5",
    },
    {
        "label": "Beneficial ownership reports",
        "value": "SC 13D,SCHEDULE 13D,SC 13G,SCHEDULE 13G",
    },
    {
        "label": "Exempt offerings",
        "value": "1-A,1-A POS,1-A-W,253G1,253G2,253G3,253G4,C,D,DOS",
    },
    {
        "label": "Registration statements and prospectuses",
        "value": "10-12B,10-12G,18-12B,20FR12B,20FR12G,40-24B2,40FR12B,40FR12G,424A,424B1,424B2,424B3,424B4,424B5,424B7,424B8,424H,425,485APOS,485BPOS,485BXT,487,497,497J,497K,8-A12B,8-A12G,AW,AW WD,DEL AM,DRS,F-1,F-10,F-10EF,F-10POS,F-3,F-3ASR,F-3D,F-3DPOS,F-3MEF,F-4,F-4 POS,F-4MEF,F-6,F-6 POS,F-6EF,F-7,F-7 POS,F-8,F-8 POS,F-80,F-80POS,F-9,F-9 POS,F-N,F-X,FWP,N-2,POS AM,POS EX,POS462B,POS462C,POSASR,RW,RW WD,S-1,S-11,S-11MEF,S-1MEF,S-20,S-3,S-3ASR,S-3D,S-3DPOS,S-3MEF,S-4,S-4 POS,S-4EF,S-4MEF,S-6,S-8,S-8 POS,S-B,S-BMEF,SF-1,SF-3,SUPPL,UNDER",
    },
    {"label": "Filing review correspondence", "value": "CORRESP,DOSLTR,DRSLTR,UPLOAD"},
    {
        "label": "SEC orders and notices",
        "value": "40-APP,CT ORDER,EFFECT,QUALIF,REVOKED",
    },
    {
        "label": "Proxy materials",
        "value": "ARS,DEF 14A,DEF 14C,DEFA14A,DEFA14C,DEFC14A,DEFC14C,DEFM14A,DEFM14C,DEFN14A,DEFR14A,DEFR14C,DFAN14A,DFRN14A,PRE 14A,PRE 14C,PREC14A,PREC14C,PREM14A,PREM14C,PREN14A,PRER14A,PRER14C,PRRN14A,PX14A6G,PX14A6N,SC 14N",
    },
    {
        "label": "Tender offers and going private transactions",
        "value": "CB,SC 13E1,SC 13E3,SC 14D9,SC 14F1,SC TO-C,SC TO-I,SC TO-T,SC13E4F,SC14D9C,SC14D9F,SC14D1F",
    },
    {"label": "Trust indenture filings", "value": "305B2,T-3"},
]

FTS_LOCATIONS = [
    {"label": "Alabama", "value": "AL"},
    {"label": "Alaska", "value": "AK"},
    {"label": "Arizona", "value": "AZ"},
    {"label": "Arkansas", "value": "AR"},
    {"label": "California", "value": "CA"},
    {"label": "Colorado", "value": "CO"},
    {"label": "Connecticut", "value": "CT"},
    {"label": "Delaware", "value": "DE"},
    {"label": "District of Columbia", "value": "DC"},
    {"label": "Florida", "value": "FL"},
    {"label": "Georgia", "value": "GA"},
    {"label": "Hawaii", "value": "HI"},
    {"label": "Idaho", "value": "ID"},
    {"label": "Illinois", "value": "IL"},
    {"label": "Indiana", "value": "IN"},
    {"label": "Iowa", "value": "IA"},
    {"label": "Kansas", "value": "KS"},
    {"label": "Kentucky", "value": "KY"},
    {"label": "Louisiana", "value": "LA"},
    {"label": "Maine", "value": "ME"},
    {"label": "Maryland", "value": "MD"},
    {"label": "Massachusetts", "value": "MA"},
    {"label": "Michigan", "value": "MI"},
    {"label": "Minnesota", "value": "MN"},
    {"label": "Mississippi", "value": "MS"},
    {"label": "Missouri", "value": "MO"},
    {"label": "Montana", "value": "MT"},
    {"label": "Nebraska", "value": "NE"},
    {"label": "Nevada", "value": "NV"},
    {"label": "New Hampshire", "value": "NH"},
    {"label": "New Jersey", "value": "NJ"},
    {"label": "New Mexico", "value": "NM"},
    {"label": "New York", "value": "NY"},
    {"label": "North Carolina", "value": "NC"},
    {"label": "North Dakota", "value": "ND"},
    {"label": "Ohio", "value": "OH"},
    {"label": "Oklahoma", "value": "OK"},
    {"label": "Oregon", "value": "OR"},
    {"label": "Pennsylvania", "value": "PA"},
    {"label": "Rhode Island", "value": "RI"},
    {"label": "South Carolina", "value": "SC"},
    {"label": "South Dakota", "value": "SD"},
    {"label": "Tennessee", "value": "TN"},
    {"label": "Texas", "value": "TX"},
    {"label": "United States", "value": "X1"},
    {"label": "Utah", "value": "UT"},
    {"label": "Vermont", "value": "VT"},
    {"label": "Virginia", "value": "VA"},
    {"label": "Washington", "value": "WA"},
    {"label": "West Virginia", "value": "WV"},
    {"label": "Wisconsin", "value": "WI"},
    {"label": "Wyoming", "value": "WY"},
    {"label": "Alberta, Canada", "value": "A0"},
    {"label": "British Columbia, Canada", "value": "A1"},
    {"label": "Canada (Federal Level)", "value": "Z4"},
    {"label": "Manitoba, Canada", "value": "A2"},
    {"label": "New Brunswick, Canada", "value": "A3"},
    {"label": "Newfoundland, Canada", "value": "A4"},
    {"label": "Nova Scotia, Canada", "value": "A5"},
    {"label": "Ontario, Canada", "value": "A6"},
    {"label": "Prince Edward Island, Canada", "value": "A7"},
    {"label": "Quebec, Canada", "value": "A8"},
    {"label": "Saskatchewan, Canada", "value": "A9"},
    {"label": "Yukon, Canada", "value": "B0"},
    {"label": "Afghanistan", "value": "B2"},
    {"label": "Aland Islands", "value": "Y6"},
    {"label": "Albania", "value": "B3"},
    {"label": "Algeria", "value": "B4"},
    {"label": "American Samoa", "value": "B5"},
    {"label": "Andorra", "value": "B6"},
    {"label": "Angola", "value": "B7"},
    {"label": "Anguilla", "value": "1A"},
    {"label": "Antarctica", "value": "B8"},
    {"label": "Antigua and Barbuda", "value": "B9"},
    {"label": "Argentina", "value": "C1"},
    {"label": "Armenia", "value": "1B"},
    {"label": "Aruba", "value": "1C"},
    {"label": "Australia", "value": "C3"},
    {"label": "Austria", "value": "C4"},
    {"label": "Azerbaijan", "value": "1D"},
    {"label": "Bahamas", "value": "C5"},
    {"label": "Bahrain", "value": "C6"},
    {"label": "Bangladesh", "value": "C7"},
    {"label": "Barbados", "value": "C8"},
    {"label": "Belarus", "value": "1F"},
    {"label": "Belgium", "value": "C9"},
    {"label": "Belize", "value": "D1"},
    {"label": "Benin", "value": "G6"},
    {"label": "Bermuda", "value": "D0"},
    {"label": "Bhutan", "value": "D2"},
    {"label": "Bolivia", "value": "D3"},
    {"label": "Bosnia and Herzegovina", "value": "1E"},
    {"label": "Botswana", "value": "B1"},
    {"label": "Bouvet Island", "value": "D4"},
    {"label": "Brazil", "value": "D5"},
    {"label": "British Indian Ocean Territory", "value": "D6"},
    {"label": "Brunei Darussalam", "value": "D9"},
    {"label": "Bulgaria", "value": "E0"},
    {"label": "Burkina Faso", "value": "X2"},
    {"label": "Burundi", "value": "E2"},
    {"label": "Cambodia", "value": "E3"},
    {"label": "Cameroon", "value": "E4"},
    {"label": "Cape Verde", "value": "E8"},
    {"label": "Cayman Islands", "value": "E9"},
    {"label": "Central African Republic", "value": "F0"},
    {"label": "Chad", "value": "F2"},
    {"label": "Chile", "value": "F3"},
    {"label": "China", "value": "F4"},
    {"label": "Christmas Island", "value": "F6"},
    {"label": "Cocos (Keeling) Islands", "value": "F7"},
    {"label": "Colombia", "value": "F8"},
    {"label": "Comoros", "value": "F9"},
    {"label": "Congo", "value": "G0"},
    {"label": "Congo, the Democratic Republic of the", "value": "Y3"},
    {"label": "Cook Islands", "value": "G1"},
    {"label": "Costa Rica", "value": "G2"},
    {"label": "Cote D'ivoire ", "value": "L7"},
    {"label": "Croatia", "value": "1M"},
    {"label": "Cuba", "value": "G3"},
    {"label": "Cyprus", "value": "G4"},
    {"label": "Czech Republic", "value": "2N"},
    {"label": "Denmark", "value": "G7"},
    {"label": "Djibouti", "value": "1G"},
    {"label": "Dominica", "value": "G9"},
    {"label": "Dominican Republic", "value": "G8"},
    {"label": "Ecuador", "value": "H1"},
    {"label": "Egypt", "value": "H2"},
    {"label": "El Salvador", "value": "H3"},
    {"label": "Equatorial Guinea", "value": "H4"},
    {"label": "Eritrea", "value": "1J"},
    {"label": "Estonia", "value": "1H"},
    {"label": "Ethiopia", "value": "H5"},
    {"label": "Falkland Islands (Malvinas)", "value": "H7"},
    {"label": "Faroe Islands", "value": "H6"},
    {"label": "Fiji", "value": "H8"},
    {"label": "Finland", "value": "H9"},
    {"label": "France", "value": "I0"},
    {"label": "French Guiana", "value": "I3"},
    {"label": "French Polynesia", "value": "I4"},
    {"label": "French Southern Territories", "value": "2C"},
    {"label": "Gabon", "value": "I5"},
    {"label": "Gambia", "value": "I6"},
    {"label": "Georgia (country)", "value": "2Q"},
    {"label": "Germany", "value": "2M"},
    {"label": "Ghana", "value": "J0"},
    {"label": "Gibraltar", "value": "J1"},
    {"label": "Greece", "value": "J3"},
    {"label": "Greenland", "value": "J4"},
    {"label": "Grenada", "value": "J5"},
    {"label": "Guadeloupe", "value": "J6"},
    {"label": "Guam", "value": "GU"},
    {"label": "Guatemala", "value": "J8"},
    {"label": "Guernsey", "value": "Y7"},
    {"label": "Guinea", "value": "J9"},
    {"label": "Guinea-bissau", "value": "S0"},
    {"label": "Guyana", "value": "K0"},
    {"label": "Haiti", "value": "K1"},
    {"label": "Heard Island and Mcdonald Islands", "value": "K4"},
    {"label": "Holy See (Vatican City State)", "value": "X4"},
    {"label": "Honduras", "value": "K2"},
    {"label": "Hong Kong", "value": "K3"},
    {"label": "Hungary", "value": "K5"},
    {"label": "Iceland", "value": "K6"},
    {"label": "India", "value": "K7"},
    {"label": "Indonesia", "value": "K8"},
    {"label": "Iran, Islamic Republic of", "value": "K9"},
    {"label": "Iraq", "value": "L0"},
    {"label": "Ireland", "value": "L2"},
    {"label": "Isle of Man", "value": "Y8"},
    {"label": "Israel", "value": "L3"},
    {"label": "Italy", "value": "L6"},
    {"label": "Jamaica", "value": "L8"},
    {"label": "Japan", "value": "M0"},
    {"label": "Jersey", "value": "Y9"},
    {"label": "Jordan", "value": "M2"},
    {"label": "Kazakhstan", "value": "1P"},
    {"label": "Kenya", "value": "M3"},
    {"label": "Kiribati", "value": "J2"},
    {"label": "Korea, Democratic People's Republic of ", "value": "M4"},
    {"label": "Korea, Republic of", "value": "M5"},
    {"label": "Kuwait", "value": "M6"},
    {"label": "Kyrgyzstan", "value": "1N"},
    {"label": "Lao People's Democratic Republic ", "value": "M7"},
    {"label": "Latvia", "value": "1R"},
    {"label": "Lebanon", "value": "M8"},
    {"label": "Lesotho", "value": "M9"},
    {"label": "Liberia", "value": "N0"},
    {"label": "Libyan Arab Jamahiriya", "value": "N1"},
    {"label": "Liechtenstein", "value": "N2"},
    {"label": "Lithuania", "value": "1Q"},
    {"label": "Luxembourg", "value": "N4"},
    {"label": "Macau", "value": "N5"},
    {"label": "Macedonia, the Former Yugoslav Republic of", "value": "1U"},
    {"label": "Madagascar", "value": "N6"},
    {"label": "Malawi", "value": "N7"},
    {"label": "Malaysia", "value": "N8"},
    {"label": "Maldives", "value": "N9"},
    {"label": "Mali", "value": "O0"},
    {"label": "Malta", "value": "O1"},
    {"label": "Marshall Islands", "value": "1T"},
    {"label": "Martinique", "value": "O2"},
    {"label": "Mauritania", "value": "O3"},
    {"label": "Mauritius", "value": "O4"},
    {"label": "Mayotte", "value": "2P"},
    {"label": "Mexico", "value": "O5"},
    {"label": "Micronesia, Federated States of", "value": "1K"},
    {"label": "Moldova, Republic of", "value": "1S"},
    {"label": "Monaco", "value": "O9"},
    {"label": "Mongolia", "value": "P0"},
    {"label": "Montenegro", "value": "Z5"},
    {"label": "Montserrat", "value": "P1"},
    {"label": "Morocco", "value": "P2"},
    {"label": "Mozambique", "value": "P3"},
    {"label": "Myanmar", "value": "E1"},
    {"label": "Namibia", "value": "T6"},
    {"label": "Nauru", "value": "P5"},
    {"label": "Nepal", "value": "P6"},
    {"label": "Netherlands", "value": "P7"},
    {"label": "Netherlands Antilles", "value": "P8"},
    {"label": "New Caledonia", "value": "1W"},
    {"label": "New Zealand", "value": "Q2"},
    {"label": "Nicaragua", "value": "Q3"},
    {"label": "Niger", "value": "Q4"},
    {"label": "Nigeria", "value": "Q5"},
    {"label": "Niue", "value": "Q6"},
    {"label": "Norfolk Island", "value": "Q7"},
    {"label": "Northern Mariana Islands", "value": "1V"},
    {"label": "Norway", "value": "Q8"},
    {"label": "Oman", "value": "P4"},
    {"label": "Pakistan", "value": "R0"},
    {"label": "Palau", "value": "1Y"},
    {"label": "Palestinian Territory, Occupied", "value": "1X"},
    {"label": "Panama", "value": "R1"},
    {"label": "Papua New Guinea", "value": "R2"},
    {"label": "Paraguay", "value": "R4"},
    {"label": "Peru", "value": "R5"},
    {"label": "Philippines", "value": "R6"},
    {"label": "Pitcairn", "value": "R8"},
    {"label": "Poland", "value": "R9"},
    {"label": "Portugal", "value": "S1"},
    {"label": "Puerto Rico", "value": "PR"},
    {"label": "Qatar", "value": "S3"},
    {"label": "Reunion", "value": "S4"},
    {"label": "Romania", "value": "S5"},
    {"label": "Russian Federation", "value": "1Z"},
    {"label": "Rwanda", "value": "S6"},
    {"label": "Saint Barthelemy", "value": "Z0"},
    {"label": "Saint Helena", "value": "U8"},
    {"label": "Saint Kitts and Nevis", "value": "U7"},
    {"label": "Saint Lucia", "value": "U9"},
    {"label": "Saint Martin", "value": "Z1"},
    {"label": "Saint Pierre and Miquelon", "value": "V0"},
    {"label": "Saint Vincent and the Grenadines", "value": "V1"},
    {"label": "Samoa", "value": "Y0"},
    {"label": "San Marino", "value": "S8"},
    {"label": "Sao Tome and Principe", "value": "S9"},
    {"label": "Saudi Arabia", "value": "T0"},
    {"label": "Senegal", "value": "T1"},
    {"label": "Serbia", "value": "Z2"},
    {"label": "Seychelles", "value": "T2"},
    {"label": "Sierra Leone", "value": "T8"},
    {"label": "Singapore", "value": "U0"},
    {"label": "Slovakia", "value": "2B"},
    {"label": "Slovenia", "value": "2A"},
    {"label": "Solomon Islands", "value": "D7"},
    {"label": "Somalia", "value": "U1"},
    {"label": "South Africa", "value": "T3"},
    {"label": "South Georgia and the South Sandwich Islands", "value": "1L"},
    {"label": "Spain", "value": "U3"},
    {"label": "Sri Lanka", "value": "F1"},
    {"label": "Sudan", "value": "V2"},
    {"label": "Suriname", "value": "V3"},
    {"label": "Svalbard and Jan Mayen", "value": "L9"},
    {"label": "Swaziland", "value": "V6"},
    {"label": "Sweden", "value": "V7"},
    {"label": "Switzerland", "value": "V8"},
    {"label": "Syrian Arab Republic", "value": "V9"},
    {"label": "Taiwan", "value": "F5"},
    {"label": "Tajikistan", "value": "2D"},
    {"label": "Tanzania, United Republic of", "value": "W0"},
    {"label": "Thailand", "value": "W1"},
    {"label": "Timor-leste", "value": "Z3"},
    {"label": "Togo", "value": "W2"},
    {"label": "Tokelau", "value": "W3"},
    {"label": "Tonga", "value": "W4"},
    {"label": "Trinidad and Tobago", "value": "W5"},
    {"label": "Tunisia", "value": "W6"},
    {"label": "Turkey", "value": "W8"},
    {"label": "Turkmenistan", "value": "2E"},
    {"label": "Turks and Caicos Islands", "value": "W7"},
    {"label": "Tuvalu", "value": "2G"},
    {"label": "Uganda", "value": "W9"},
    {"label": "Ukraine", "value": "2H"},
    {"label": "United Arab Emirates", "value": "C0"},
    {"label": "United Kingdom", "value": "X0"},
    {"label": "United States Minor Outlying Islands", "value": "2J"},
    {"label": "Uruguay", "value": "X3"},
    {"label": "Uzbekistan", "value": "2K"},
    {"label": "Vanuatu", "value": "2L"},
    {"label": "Venezuela", "value": "X5"},
    {"label": "Viet Nam", "value": "Q1"},  # codespell:ignore nam
    {"label": "Virgin Islands, British", "value": "D8"},
    {"label": "Virgin Islands, U.s.", "value": "VI"},
    {"label": "Wallis and Futuna", "value": "X8"},
    {"label": "Western Sahara", "value": "U5"},
    {"label": "Yemen", "value": "T7"},
    {"label": "Zambia", "value": "Y4"},
    {"label": "Zimbabwe", "value": "Y5"},
    {"label": "Unknown", "value": "XX"},
]
