"""Generate minimal TS interface stubs from selected Pydantic models."""

from __future__ import annotations

from pathlib import Path

from openbb_quant_ml.models import (
    DashboardSnapshotV2,
    RunAuditResponse,
    RunLatestConstraintsResponse,
    RunLatestMetaResponse,
)

ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = ROOT / "desktop" / "src" / "types" / "quant.generated.ts"


def _emit_interface(name: str, model) -> str:  # noqa: ANN001
    lines = [f"export interface {name} {{"]
    for field_name in model.model_fields.keys():
        lines.append(f"  {field_name}: unknown;")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "// Auto-generated by qa/scripts/generate_quant_ts_types.py",
        "// Keep this file additive and import explicit interfaces from quant.ts as needed.",
        "",
        _emit_interface("RunLatestMetaGenerated", RunLatestMetaResponse),
        "",
        _emit_interface("RunLatestConstraintsGenerated", RunLatestConstraintsResponse),
        "",
        _emit_interface("DashboardSnapshotGenerated", DashboardSnapshotV2),
        "",
        _emit_interface("RunAuditGenerated", RunAuditResponse),
        "",
    ]
    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
