# Polygon Definitions
"""exhcanges_url=f"https://api.polygon.io/v3/reference/exchanges?asset_class=stocks&apiKey={api_key}"
"""


EXCHANGES = {
    "id": {
        "0": 1,
        "1": 2,
        "2": 3,
        "3": 4,
        "4": 4,
        "5": 4,
        "6": 4,
        "7": 5,
        "8": 6,
        "9": 7,
        "10": 8,
        "11": 9,
        "12": 10,
        "13": 11,
        "14": 12,
        "15": 13,
        "16": 14,
        "17": 15,
        "18": 16,
        "19": 17,
        "20": 18,
        "21": 19,
        "22": 20,
        "23": 21,
        "24": 62,
    },
    "type": {
        "0": "exchange",
        "1": "exchange",
        "2": "exchange",
        "3": "TRF",
        "4": "TRF",
        "5": "TRF",
        "6": "TRF",
        "7": "SIP",
        "8": "TRF",
        "9": "exchange",
        "10": "exchange",
        "11": "exchange",
        "12": "exchange",
        "13": "exchange",
        "14": "exchange",
        "15": "SIP",
        "16": "exchange",
        "17": "exchange",
        "18": "TRF",
        "19": "exchange",
        "20": "exchange",
        "21": "exchange",
        "22": "exchange",
        "23": "exchange",
        "24": "ORF",
    },
    "asset_class": {
        "0": "stocks",
        "1": "stocks",
        "2": "stocks",
        "3": "stocks",
        "4": "stocks",
        "5": "stocks",
        "6": "stocks",
        "7": "stocks",
        "8": "stocks",
        "9": "stocks",
        "10": "stocks",
        "11": "stocks",
        "12": "stocks",
        "13": "stocks",
        "14": "stocks",
        "15": "stocks",
        "16": "stocks",
        "17": "stocks",
        "18": "stocks",
        "19": "stocks",
        "20": "stocks",
        "21": "stocks",
        "22": "stocks",
        "23": "stocks",
        "24": "stocks",
    },
    "locale": {
        "0": "us",
        "1": "us",
        "2": "us",
        "3": "us",
        "4": "us",
        "5": "us",
        "6": "us",
        "7": "us",
        "8": "us",
        "9": "us",
        "10": "us",
        "11": "us",
        "12": "us",
        "13": "us",
        "14": "us",
        "15": "us",
        "16": "us",
        "17": "us",
        "18": "us",
        "19": "us",
        "20": "us",
        "21": "us",
        "22": "us",
        "23": "us",
        "24": "us",
    },
    "name": {
        "0": "NYSE American, LLC",
        "1": "Nasdaq OMX BX, Inc.",
        "2": "NYSE National, Inc.",
        "3": "FINRA NYSE TRF",
        "4": "FINRA Nasdaq TRF Carteret",
        "5": "FINRA Nasdaq TRF Chicago",
        "6": "FINRA Alternative Display Facility",
        "7": "Unlisted Trading Privileges",
        "8": "International Securities Exchange, LLC - Stocks",
        "9": "Cboe EDGA",
        "10": "Cboe EDGX",
        "11": "NYSE Chicago, Inc.",
        "12": "New York Stock Exchange",
        "13": "NYSE Arca, Inc.",
        "14": "Nasdaq",
        "15": "Consolidated Tape Association",
        "16": "Long-Term Stock Exchange",
        "17": "Investors Exchange",
        "18": "Cboe Stock Exchange",
        "19": "Nasdaq Philadelphia Exchange LLC",
        "20": "Cboe BYX",
        "21": "Cboe BZX",
        "22": "MIAX Pearl",
        "23": "Members Exchange",
        "24": "OTC Equity Security",
    },
    "acronym": {
        "0": "AMEX",
        "1": "",
        "2": "NSX",
        "3": "",
        "4": "",
        "5": "",
        "6": "",
        "7": "",
        "8": "",
        "9": "",
        "10": "",
        "11": "",
        "12": "",
        "13": "",
        "14": "",
        "15": "",
        "16": "",
        "17": "",
        "18": "",
        "19": "",
        "20": "",
        "21": "",
        "22": "",
        "23": "",
        "24": "",
    },
    "mic": {
        "0": "XASE",
        "1": "XBOS",
        "2": "XCIS",
        "3": "FINY",
        "4": "FINN",
        "5": "FINC",
        "6": "XADF",
        "7": "",
        "8": "XISE",
        "9": "EDGA",
        "10": "EDGX",
        "11": "XCHI",
        "12": "XNYS",
        "13": "ARCX",
        "14": "XNAS",
        "15": "",
        "16": "LTSE",
        "17": "IEXG",
        "18": "CBSX",
        "19": "XPHL",
        "20": "BATY",
        "21": "BATS",
        "22": "EPRL",
        "23": "MEMX",
        "24": "OOTC",
    },
    "operating_mic": {
        "0": "XNYS",
        "1": "XNAS",
        "2": "XNYS",
        "3": "XNYS",
        "4": "FINR",
        "5": "FINR",
        "6": "FINR",
        "7": "XNAS",
        "8": "XNAS",
        "9": "XCBO",
        "10": "XCBO",
        "11": "XNYS",
        "12": "XNYS",
        "13": "XNYS",
        "14": "XNAS",
        "15": "XNYS",
        "16": "LTSE",
        "17": "IEXG",
        "18": "XCBO",
        "19": "XNAS",
        "20": "XCBO",
        "21": "XCBO",
        "22": "MIHI",
        "23": "MEMX",
        "24": "FINR",
    },
    "participant_id": {
        "0": "A",
        "1": "B",
        "2": "C",
        "3": "D",
        "4": "D",
        "5": "D",
        "6": "D",
        "7": "E",
        "8": "I",
        "9": "J",
        "10": "K",
        "11": "M",
        "12": "N",
        "13": "P",
        "14": "T",
        "15": "S",
        "16": "L",
        "17": "V",
        "18": "W",
        "19": "X",
        "20": "Y",
        "21": "Z",
        "22": "H",
        "23": "U",
        "24": "",
    },
}
