/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UninstallRouteImport } from './routes/uninstall'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as QuantRouteImport } from './routes/quant'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as JupyterLogsRouteImport } from './routes/jupyter-logs'
import { Route as InstallationProgressRouteImport } from './routes/installation-progress'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackendsRouteImport } from './routes/backends'
import { Route as BackendLogsRouteImport } from './routes/backend-logs'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'

const UninstallRoute = UninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantRoute = QuantRouteImport.update({
  id: '/quant',
  path: '/quant',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const JupyterLogsRoute = JupyterLogsRouteImport.update({
  id: '/jupyter-logs',
  path: '/jupyter-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationProgressRoute = InstallationProgressRouteImport.update({
  id: '/installation-progress',
  path: '/installation-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendsRoute = BackendsRouteImport.update({
  id: '/backends',
  path: '/backends',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendLogsRoute = BackendLogsRouteImport.update({
  id: '/backend-logs',
  path: '/backend-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/backend-logs': typeof BackendLogsRoute
  '/backends': typeof BackendsRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRoute
  '/installation-progress': typeof InstallationProgressRoute
  '/jupyter-logs': typeof JupyterLogsRoute
  '/macro': typeof MacroRoute
  '/quant': typeof QuantRoute
  '/setup': typeof SetupRoute
  '/uninstall': typeof UninstallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/backend-logs': typeof BackendLogsRoute
  '/backends': typeof BackendsRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRoute
  '/installation-progress': typeof InstallationProgressRoute
  '/jupyter-logs': typeof JupyterLogsRoute
  '/macro': typeof MacroRoute
  '/quant': typeof QuantRoute
  '/setup': typeof SetupRoute
  '/uninstall': typeof UninstallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/backend-logs': typeof BackendLogsRoute
  '/backends': typeof BackendsRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRoute
  '/installation-progress': typeof InstallationProgressRoute
  '/jupyter-logs': typeof JupyterLogsRoute
  '/macro': typeof MacroRoute
  '/quant': typeof QuantRoute
  '/setup': typeof SetupRoute
  '/uninstall': typeof UninstallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/backend-logs'
    | '/backends'
    | '/dashboard'
    | '/environments'
    | '/installation-progress'
    | '/jupyter-logs'
    | '/macro'
    | '/quant'
    | '/setup'
    | '/uninstall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/backend-logs'
    | '/backends'
    | '/dashboard'
    | '/environments'
    | '/installation-progress'
    | '/jupyter-logs'
    | '/macro'
    | '/quant'
    | '/setup'
    | '/uninstall'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/backend-logs'
    | '/backends'
    | '/dashboard'
    | '/environments'
    | '/installation-progress'
    | '/jupyter-logs'
    | '/macro'
    | '/quant'
    | '/setup'
    | '/uninstall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BackendLogsRoute: typeof BackendLogsRoute
  BackendsRoute: typeof BackendsRoute
  DashboardRoute: typeof DashboardRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  InstallationProgressRoute: typeof InstallationProgressRoute
  JupyterLogsRoute: typeof JupyterLogsRoute
  MacroRoute: typeof MacroRoute
  QuantRoute: typeof QuantRoute
  SetupRoute: typeof SetupRoute
  UninstallRoute: typeof UninstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uninstall': {
      id: '/uninstall'
      path: '/uninstall'
      fullPath: '/uninstall'
      preLoaderRoute: typeof UninstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quant': {
      id: '/quant'
      path: '/quant'
      fullPath: '/quant'
      preLoaderRoute: typeof QuantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jupyter-logs': {
      id: '/jupyter-logs'
      path: '/jupyter-logs'
      fullPath: '/jupyter-logs'
      preLoaderRoute: typeof JupyterLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation-progress': {
      id: '/installation-progress'
      path: '/installation-progress'
      fullPath: '/installation-progress'
      preLoaderRoute: typeof InstallationProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backends': {
      id: '/backends'
      path: '/backends'
      fullPath: '/backends'
      preLoaderRoute: typeof BackendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-logs': {
      id: '/backend-logs'
      path: '/backend-logs'
      fullPath: '/backend-logs'
      preLoaderRoute: typeof BackendLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BackendLogsRoute: BackendLogsRoute,
  BackendsRoute: BackendsRoute,
  DashboardRoute: DashboardRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  InstallationProgressRoute: InstallationProgressRoute,
  JupyterLogsRoute: JupyterLogsRoute,
  MacroRoute: MacroRoute,
  QuantRoute: QuantRoute,
  SetupRoute: SetupRoute,
  UninstallRoute: UninstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
