"""Quant ML service helpers."""

from openbb_quant_ml.service.dashboard_metrics import (
    get_alerts_current,
    get_alerts_history,
    get_dashboard_health,
    get_model_ic_decay,
    get_model_shap,
    get_performance_regime,
    get_performance_rolling,
    get_portfolio_exposure,
    get_portfolio_risk,
    get_prediction_distribution,
    get_regime_current,
    get_regime_history,
    refresh_alerts_for_run,
)
from openbb_quant_ml.service.execution import (
    get_execution_fills_history,
    get_execution_orders_current,
    get_execution_pnl,
    get_execution_positions_current,
    get_risk_events,
    get_risk_limits,
    preview_execution_orders,
    risk_check_pretrade,
    submit_execution_orders,
)
from openbb_quant_ml.service.macro_service import (
    evaluate_expression_response,
    get_alerts_response as get_macro_alerts,
    get_catalog_response as get_macro_catalog,
    get_copper_gold_preset_response,
    get_market_ratio_response,
    get_market_rolling_corr_response,
    get_regime_response as get_macro_regime,
    get_regime_state_response as get_macro_regime_state,
    get_series_multi_response as get_macro_series_multi,
    get_series_response as get_macro_series,
    list_derived_response as get_macro_derived,
    register_catalog_response as register_macro_catalog,
    save_derived_response as save_macro_derived,
    search_catalog_response as search_macro_catalog,
    trigger_update_response as update_macro_series,
)
from openbb_quant_ml.service.ops_status import get_ops_status_response
from openbb_quant_ml.service.portfolio_policy import get_portfolio_policy_response
from openbb_quant_ml.service.pipeline import (
    build_signals,
    get_feature_importance,
    get_model_ic,
    get_model_performance,
    get_model_regime,
    get_portfolio_current,
    get_rebalance_history,
    get_predictions_latest,
    get_run,
    get_summary,
    get_universe,
    get_universe_exclusions,
    get_universe_snapshot,
    run_backtest_for_run,
    submit_training,
)
from openbb_quant_ml.service.runtime_pointer import get_promoted_model_response
from openbb_quant_ml.service.walkforward_backtest import (
    get_walkforward_backtest_status,
    submit_walkforward_backtest,
)

__all__ = [
    "get_alerts_current",
    "get_alerts_history",
    "get_dashboard_health",
    "build_signals",
    "get_feature_importance",
    "get_model_ic",
    "get_model_ic_decay",
    "get_model_shap",
    "get_model_performance",
    "get_model_regime",
    "get_performance_regime",
    "get_performance_rolling",
    "get_portfolio_current",
    "get_rebalance_history",
    "get_portfolio_exposure",
    "get_portfolio_risk",
    "get_prediction_distribution",
    "get_regime_current",
    "get_regime_history",
    "get_predictions_latest",
    "get_run",
    "get_summary",
    "get_universe",
    "get_universe_snapshot",
    "get_universe_exclusions",
    "refresh_alerts_for_run",
    "preview_execution_orders",
    "submit_execution_orders",
    "get_execution_orders_current",
    "get_execution_fills_history",
    "get_execution_positions_current",
    "get_execution_pnl",
    "get_risk_limits",
    "risk_check_pretrade",
    "get_risk_events",
    "run_backtest_for_run",
    "submit_training",
    "submit_walkforward_backtest",
    "get_walkforward_backtest_status",
    "get_promoted_model_response",
    "get_macro_catalog",
    "search_macro_catalog",
    "register_macro_catalog",
    "get_macro_series",
    "get_macro_series_multi",
    "evaluate_expression_response",
    "get_macro_regime",
    "get_macro_regime_state",
    "get_macro_alerts",
    "save_macro_derived",
    "get_macro_derived",
    "update_macro_series",
    "get_market_ratio_response",
    "get_market_rolling_corr_response",
    "get_copper_gold_preset_response",
    "get_ops_status_response",
    "get_portfolio_policy_response",
]
