"""OpenBB EIA Provider Module Constants."""

from typing import Literal

WpsrCategoryType = Literal[
    "balance_sheet",
    "inputs_and_production",
    "refiner_and_blender_net_production",
    "crude_petroleum_stocks",
    "gasoline_fuel_stocks",
    "total_gasoline_by_sub_padd",
    "distillate_fuel_oil_stocks",
    "imports",
    "imports_by_country",
    "weekly_estimates",
    "spot_prices_crude_gas_heating",
    "spot_prices_diesel_jet_fuel_propane",
    "retail_prices",
]
WpsrCategoryChoices = [
    "balance_sheet",
    "inputs_and_production",
    "refiner_and_blender_net_production",
    "crude_petroleum_stocks",
    "gasoline_fuel_stocks",
    "total_gasoline_by_sub_padd",
    "distillate_fuel_oil_stocks",
    "imports",
    "imports_by_country",
    "weekly_estimates",
    "spot_prices_crude_gas_heating",
    "spot_prices_diesel_jet_fuel_propane",
    "retail_prices",
]
WpsrTableType = Literal[
    "all",
    "conventional_gas",
    "crude",
    "crude_production",
    "crude_production_avg",
    "diesel",
    "ethanol_plant_production",
    "ethanol_plant_production_avg",
    "exports",
    "exports_avg",
    "heating_oil",
    "imports",
    "imports_avg",
    "imports_by_country",
    "imports_by_country_avg",
    "inputs_and_utilization",
    "inputs_and_utilization_avg",
    "jet_fuel",
    "monthly",
    "net_imports_inc_spr_avg",
    "net_imports_incl_spr",
    "net_production",
    "net_production_avg",
    "net_production_by_product",
    "net_production_by_production_avg",
    "product_by_region",
    "product_by_region_avg",
    "product_supplied",
    "product_supplied_avg",
    "propane",
    "rbob",
    "refiner_blender_net_production",
    "refiner_blender_net_production_avg",
    "stocks",
    "supply",
    "supply_avg",
    "ulta_low_sulfur_distillate_reflassification",
    "ulta_low_sulfur_distillate_reflassification_avg",
    "weekly",
]
WpsrTableChoices = [
    "all",
    "conventional_gas",
    "crude",
    "crude_production",
    "crude_production_avg",
    "diesel",
    "ethanol_plant_production",
    "ethanol_plant_production_avg",
    "exports",
    "exports_avg",
    "heating_oil",
    "imports",
    "imports_avg",
    "imports_by_country",
    "imports_by_country_avg",
    "inputs_and_utilization",
    "inputs_and_utilization_avg",
    "jet_fuel",
    "monthly",
    "net_imports_inc_spr_avg",
    "net_imports_incl_spr",
    "net_production",
    "net_production_avg",
    "net_production_by_product",
    "net_production_by_production_avg",
    "product_by_region",
    "product_by_region_avg",
    "product_supplied",
    "product_supplied_avg",
    "propane",
    "rbob",
    "refiner_blender_net_production",
    "refiner_blender_net_production_avg",
    "stocks",
    "supply",
    "supply_avg",
    "ulta_low_sulfur_distillate_reflassification",
    "ulta_low_sulfur_distillate_reflassification_avg",
    "weekly",
]
WpsrFileMap = {
    "balance_sheet": "https://ir.eia.gov/wpsr/psw01.xls",
    "inputs_and_production": "https://ir.eia.gov/wpsr/psw02.xls",
    "refiner_and_blender_net_production": "https://ir.eia.gov/wpsr/psw03.xls",
    "crude_petroleum_stocks": "https://ir.eia.gov/wpsr/psw04.xls",
    "gasoline_fuel_stocks": "https://ir.eia.gov/wpsr/psw05.xls",
    "total_gasoline_by_sub_padd": "https://ir.eia.gov/wpsr/psw05a.xls",
    "distillate_fuel_oil_stocks": "https://ir.eia.gov/wpsr/psw06.xls",
    "imports": "https://ir.eia.gov/wpsr/psw07.xls",
    "imports_by_country": "https://ir.eia.gov/wpsr/psw08.xls",
    "weekly_estimates": "https://ir.eia.gov/wpsr/psw09.xls",
    "spot_prices_crude_gas_heating": "https://ir.eia.gov/wpsr/psw11.xls",
    "spot_prices_diesel_jet_fuel_propane": "https://ir.eia.gov/wpsr/psw12.xls",
    "retail_prices": "https://ir.eia.gov/wpsr/psw14.xls",
}
WpsrTableMap = {
    "balance_sheet": {
        "stocks": "Data 1",
        "supply": "Data 2",
        "supply_avg": "Data 3",
    },
    "inputs_and_production": {
        "product_by_region": "Data 1",
        "product_by_region_avg": "Data 2",
    },
    "refiner_blender_net_production": {
        "net_production": "Data 1",
        "net_production_avg": "Data 2",
    },
    "crude_petroleum_stocks": {
        "stocks": "Data 1",
    },
    "gasoline_fuel_stocks": {
        "stocks": "Data 1",
    },
    "total_gasoline_by_sub_padd": {
        "stocks": "Data 1",
    },
    "distillate_fuel_oil_stocks": {
        "stocks": "Data 1",
    },
    "imports": {
        "imports": "Data 1",
        "imports_avg": "Data 2",
    },
    "imports_by_country": {
        "imports_by_country": "Data 1",
        "imports_by_country_avg": "Data 2",
    },
    "weekly_estimates": {
        "crude_production": "Data 1",
        "inputs_and_utilization": "Data 2",
        "refiner_blender_net_production": "Data 3",
        "net_production_by_product": "Data 4",
        "ethanol_plant_production": "Data 5",
        "stocks": "Data 6",
        "imports": "Data 7",
        "exports": "Data 8",
        "net_imports_incl_spr": "Data 9",
        "product_supplied": "Data 10",
        "ulta_low_sulfur_distillate_reflassification": "Data 11",
        "crude_production_avg": "Data 12",
        "inputs_utilization_avg": "Data 13",
        "refiner_blender_net_production_avg": "Data 14",
        "net_production_by_production_avg": "Data 15",
        "ethanol_plant_production_avg": "Data 16",
        "imports_avg": "Data 17",
        "exports_avg": "Data 18",
        "net_imports_inc_spr_avg": "Data 19",
        "product_supplied_avg": "Data 20",
        "ulta_low_sulfur_distillate_reflassification_avg": "Data 21",
    },
    "spot_prices_crude_gas_heating": {
        "crude": "Data 1",
        "conventional_gas": "Data 2",
        "rbob": "Data 3",
        "heating_oil": "Data 4",
    },
    "spot_prices_diesel_jet_fuel_propane": {
        "diesel": "Data 1",
        "jet_fuel": "Data 2",
        "propane": "Data 3",
    },
    "retail_prices": {
        "weekly": "Data 1",
        "monthly": "Data 2",
    },
}
