"""Typed base shared by the metadata mixins.

At runtime this is an empty class; under type checking it declares the
singleton's cached attributes and the cross-mixin methods so each mixin can
reference ``self.<attr>`` / ``self.<method>()`` without the checker flagging
an unresolved name. ``EcbMetadata`` and every mixin inherit from it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:

    class MetadataBase:
        """Type-only declaration of the shared singleton surface."""

        dataflows: dict[str, dict]
        datastructures: dict[str, dict]
        codelists: dict[str, dict[str, str]]
        concepts: dict[str, str]
        categories: dict[str, dict]
        dataflow_categories: dict[str, list[str]]
        category_dataflows: dict[str, list[str]]
        presentation_tables: dict[str, dict]
        row_labels: dict[str, str]
        dataflow_constraints: dict[str, dict[str, list[str]]]
        _dataflow_parameters_cache: dict[str, dict]

        # --- _cache_mixin ---
        def _load_from_cache(self) -> bool: ...

        # --- _loader_mixin ---
        def _fetch_codelist_live(
            self, codelist_id: str, agency: str = ..., version: str = ...
        ) -> dict[str, str]: ...
        def _fetch_available_constraint(
            self, flow_ref: str, key: str
        ) -> dict[str, list[str]]: ...

        # --- _query_mixin ---
        def get_dataflow(self, dataflow_id: str) -> dict: ...
        def get_dsd_for_dataflow(self, dataflow_id: str) -> dict: ...
        def get_codelist(
            self, codelist_id: str, agency: str = ...
        ) -> dict[str, str]: ...
        def concept_name(self, concept_id: str | None) -> str: ...
        def get_dataflow_dimensions(self, dataflow_id: str) -> list[dict]: ...
        def get_dataflow_parameters(
            self, dataflow_id: str
        ) -> dict[str, list[dict]]: ...
        def resolve_dimension_values(
            self, dataflow_id: str, dimension_id: str
        ) -> list[dict]: ...

        # --- _search_mixin ---
        def list_dataflows(self) -> list[dict]: ...
        def search_dataflows(self, query: str) -> list[dict]: ...

        # --- _category_mixin ---
        def list_topics(self) -> list[dict]: ...
        def get_topic_dataflows(self, category_id: str) -> list[str]: ...
        def topics_for_dataflow(self, dataflow_id: str) -> list[str]: ...

        # --- _table_mixin ---
        def list_tables(self) -> list[dict]: ...
        def list_tables_for_dataflow(self, dataflow_id: str) -> list[dict]: ...
        def get_table(self, table_id: str) -> dict: ...
        def get_table_structure(self, table_id: str) -> list[dict]: ...
        def get_table_dimensions(self, table_id: str) -> list[str]: ...
        def get_table_default_context(self, table_id: str) -> dict[str, str]: ...
        def get_table_valid_context(self, table_id: str) -> dict[str, list[str]]: ...
        def resolve_node_label(self, node: dict) -> str: ...
        def dimension_for_codelist(
            self, dataflow_id: str, codelist_id: str
        ) -> str | None: ...

else:

    class MetadataBase:
        """Runtime no-op base."""
