"""Series ID Dictionaries for Quandl Provider."""

SP500MULTIPLES = {
    "Shiller PE Ratio by Month": "MULTPL/SHILLER_PE_RATIO_MONTH",
    "Shiller PE Ratio by Year": "MULTPL/SHILLER_PE_RATIO_YEAR",
    "PE Ratio by Year": "MULTPL/SP500_PE_RATIO_YEAR",
    "PE Ratio by Month": "MULTPL/SP500_PE_RATIO_MONTH",
    "Dividend by Year": "MULTPL/SP500_DIV_YEAR",
    "Dividend by Month": "MULTPL/SP500_DIV_MONTH",
    "Dividend Growth by Quarter": "MULTPL/SP500_DIV_GROWTH_QUARTER",
    "Dividend Growth by Year": "MULTPL/SP500_DIV_GROWTH_YEAR",
    "Dividend Yield by Year": "MULTPL/SP500_DIV_YIELD_YEAR",
    "Dividend Yield by Month": "MULTPL/SP500_DIV_YIELD_MONTH",
    "Earnings by Year": "MULTPL/SP500_EARNINGS_YEAR",
    "Earnings by Month": "MULTPL/SP500_EARNINGS_MONTH",
    "Earnings Growth by Year": "MULTPL/SP500_EARNINGS_GROWTH_YEAR",
    "Earnings Growth by Quarter": "MULTPL/SP500_EARNINGS_GROWTH_QUARTER",
    "Real Earnings Growth by Year": "MULTPL/SP500_REAL_EARNINGS_GROWTH_YEAR",
    "Real Earnings Growth by Quarter": "MULTPL/SP500_REAL_EARNINGS_GROWTH_QUARTER",
    "Earnings Yield by Year": "MULTPL/SP500_EARNINGS_YIELD_YEAR",
    "Earnings Yield by Month": "MULTPL/SP500_EARNINGS_YIELD_MONTH",
    "Real Price by Year": "MULTPL/SP500_REAL_PRICE_YEAR",
    "Real Price by Month": "MULTPL/SP500_REAL_PRICE_MONTH",
    "Inflation Adjusted Price by Year": "MULTPL/SP500_INFLADJ_YEAR",
    "Inflation Adjusted Price by Month": "MULTPL/SP500_INFLADJ_MONTH",
    "Sales by Year": "MULTPL/SP500_SALES_YEAR",
    "Sales by Quarter": "MULTPL/SP500_SALES_QUARTER",
    "Sales Growth by Year": "MULTPL/SP500_SALES_GROWTH_YEAR",
    "Sales Growth by Quarter": "MULTPL/SP500_SALES_GROWTH_Quarter",
    "Real Sales by Year": "MULTPL/SP500_REAL_SALES_YEAR",
    "Real Sales by Quarter": "MULTPL/SP500_REAL_SALES_QUARTER",
    "Real Sales Growth by Year": "MULTPL/SP500_REAL_SALES_GROWTH_YEAR",
    "Real Sales Growth by Quarter": "MULTPL/SP500_REAL_SALES_GROWTH_QUARTER",
    "Price to Sales Ratio by Year": "MULTPL/SP500_PSR_YEAR",
    "Price to Sales Ratio by Quarter": "MULTPL/SP500_PSR_QUARTER",
    "Price to Book Value Ratio by Year": "MULTPL/SP500_PBV_RATIO_YEAR",
    "Price to Book Value Ratio by Quarter": "MULTPL/SP500_PBV_RATIO_QUARTER",
    "Book Value per Share by Year": "MULTPL/SP500_BVPS_YEAR",
    "Book Value per Share by Quarter": "MULTPL/SP500_BVPS_QUARTER",
}
