"""Tradier Provider Constants"""

STOCK_EXCHANGES = {
    "A": "NYSE MKT",
    "B": "NASDAQ OMX BX",
    "C": "National Stock Exchange",
    "D": "FINRA ADF",
    "E": "Market Independent (Generated by Nasdaq SIP)",
    "F": "Mutual Funds/Money Markets (NASDAQ)",
    "I": "International Securities Exchange",
    "J": "Direct Edge A",
    "K": "Direct Edge X",
    "L": "Long Term Stock Exchange",
    "M": "Chicago Stock Exchange",
    "N": "NYSE",
    "P": "NYSE Arca",
    "Q": "NASDAQ OMX",
    "S": "NASDAQ Small Cap",
    "T": "NASDAQ Int",
    "U": "OTCBB",
    "V": "OTC other",
    "W": "CBOE",
    "X": "NASDAQ OMX PSX",
    "G": "GLOBEX",
    "Y": "BATS Y-Exchange",
    "Z": "BATS",
}

OPTIONS_EXCHANGES = {
    "A": "NYSE Amex Options",
    "B": "BOX Options Exchange",
    "C": "Chicago Board Options Exchange (CBOE)",
    "H": "ISE Gemini",
    "I": "International Securities Exchange (ISE)",
    "M": "MIAX Options Exchange",
    "N": "NYSE Arca Options",
    "O": "Options Price Reporting Authority (OPRA)",
    "P": "MIAX PEARL",
    "Q": "NASDAQ Options Market",
    "T": "NASDAQ OMX BX",
    "W": "C2 Options Exchange",
    "X": "NASDAQ OMX PHLX",
    "Z": "BATS Options Market",
}

INTERVALS_DICT = {
    "1m": "1min",
    "5m": "5min",
    "15m": "15min",
    "1d": "daily",
    "1W": "weekly",
    "1M": "monthly",
}
