POST http://127.0.0.1:8000/
{
    "attachments":[],
    "avatar_url":null,
    "created_at":1646239509,
    "group_id":"85723258",
    "id":"164623950968155026",
    "name":"StonksBot",
    "sender_id":"866907",
    "sender_type":"bot",
    "source_guid":"0be5d3b07c76013a1338420a77b230c5",
    "system":false,
    "text":"!ta-kc/z/ema",
    "user_id":"866907"
}
