[project]
name = "openbb"
version = "5.0.0"
description = "Investment research for everyone, anywhere."
authors = [{ name = "OpenBB Team", email = "hello@openbb.co" }]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "openbb-core[flask,pandas]>=2.0.1",
    "openbb-devtools>=2.0.1",
    "openbb-mcp-server[cli]>=2.0.1",
    "openbb-news>=2.0.0",
    "openbb-platform-api>=2.0.1",
    "openbb-charting[pywry]>=4.0.0",
    "openbb-bls>=2.0.0",
    "openbb-cboe[charting]>=2.0.0",
    "openbb-cftc>=2.0.0",
    "openbb-deribit>=2.0.0",
    "openbb-ecb>=2.0.0",
    "openbb-us-eia>=2.0.0",
    "openbb-famafrench>=2.0.0",
    "openbb-federal-reserve>=2.0.0",
    "openbb-finra>=2.0.0",
    "openbb-fred>=2.0.0",
    "openbb-government-us>=2.0.0",
    "openbb-imf[charting]>=3.0.0",
    "openbb-jodi>=2.0.0",
    "openbb-nasdaq>=2.0.0",
    "openbb-oecd>=2.0.0",
    "openbb-sec>=2.0.0",
    "openbb-tmx[all,builder,charting]>=2.0.0",
    "openbb-cli[all,charting,interactive]>=2.0.1",
]

[project.optional-dependencies]
routers = [
    "openbb-commodity>=2.0.0",
    "openbb-crypto>=2.0.0",
    "openbb-currency>=2.0.0",
    "openbb-derivatives>=2.0.0",
    "openbb-econometrics>=2.0.0",
    "openbb-economy>=2.0.0",
    "openbb-equity>=2.0.0",
    "openbb-etf>=2.0.0",
    "openbb-fixedincome>=2.0.0",
    "openbb-index>=2.0.0",
    "openbb-quantitative>=2.0.0",
    "openbb-technical>=2.0.1",
]

[project.urls]
Homepage = "https://openbb.co"
Repository = "https://github.com/OpenBB-finance/OpenBB"
Documentation = "https://docs.openbb.co"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.hatch.build.targets.sdist]
only-include = ["README.md", "pyproject.toml"]
